EJERCICIOS NUMPY


In [1]:
import numpy as np
import random as rd

Crear un arreglo de Numpy con 10 elementos aleatorios del 1 al 100.

In [10]:
arr1 = np.random.randint(1 , 101, size =10)
arr1

array([25, 39, 51, 73, 47, 68,  1, 18, 72, 49])

Crear un arreglo de Numpy de forma (5,5) con valores aleatorios del 1 al 10.


In [14]:
arr2 = np.random.randint(1, 11, size=(5,5))
arr2

array([[10,  4,  6,  5,  2],
       [ 5,  4,  2,  9,  7],
       [ 9, 10,  4,  9,  6],
       [ 8,  7,  1,  5,  4],
       [ 2,  8, 10,  8,  7]])

Crear un arreglo de Numpy de forma (3,3) con valores igual a 1 en la diagonal y 0 en las otras posiciones.



In [18]:
arr3 = np.eye(5)
arr3

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Crear un arreglo de Numpy con los números impares del 1 al 20.



In [26]:
arr = np.arange(1, 21, 2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


In [28]:
lista = []
for i in range (1,21):
    if i%2 == 1:
        lista.append(i)

#print(np.array(lista))
arr4=np.array(lista)
print(arr4)


[ 1  3  5  7  9 11 13 15 17 19]


Crear un arreglo de Numpy de forma (4,4) con los números enteros del 1 al 16, y luego convertirlo en una matriz de 2x8.



In [33]:
arr5 = np.arange(1,17).reshape(4,4)
print(arr5)
arr5 = arr5.reshape(2,8)
print(arr5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


Crear dos arreglos de Numpy, uno con valores del 1 al 5 y otro con valores del 6 al 10. Luego, concatenarlos horizontalmente y verticalmente.



In [48]:
arr6_1=np.arange(0,5)
arr6_2=np.arange(5,10) 
print('arreglo 1 ',arr6_1)
print('arreglo 2 ',arr6_2)

arr6_3=np.hstack((arr6_1,arr6_2)) 
print('arreglo concatenado horizontal ',arr6_3)
arr6_4=np.vstack((arr6_1,arr6_2))
print('arreglo concatenado vertical \n', arr6_4)

arreglo 1  [0 1 2 3 4]
arreglo 2  [5 6 7 8 9]
arreglo concatenado horizontal  [0 1 2 3 4 5 6 7 8 9]
arreglo concatenado vertical 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


Crear un arreglo de Numpy con 10 elementos aleatorios, y luego ordenarlos de mayor a menor.



In [61]:
arr7=np.random.randint(0,100, size = 10)
print('arreglo original ',arr7)
arr7_1=np.sort(arr7)#ordena de menor a mayor por default
print('arreglo ordenado de menor a mayor (default) ',arr7_1)
arr7_2=np.sort(arr7)[::-1]
print('arreglo ordenado de mayor a menor usando [::-1] ',arr7_2)

arreglo original  [45 68 49 22 17 13  9 23 68 17]
arreglo ordenado de menor a mayor (default)  [ 9 13 17 17 22 23 45 49 68 68]
arreglo ordenado de mayor a menor usando [::-1]  [68 68 49 45 23 22 17 17 13  9]


Crear un arreglo de Numpy de forma (3,3) con valores aleatorios del 1 al 10, y luego calcular su transpuesta.

In [64]:
arr8=np.random.randint(0,10, size=(3,3))
print(arr8)
#arr8t=np.transpose(arr8)
arrt=arr8.T
print(arr8t)

[[5 4 7]
 [1 8 2]
 [7 8 9]]
[[5 1 9]
 [1 5 2]
 [5 8 9]]
